### PR TITLE
Update github-rs to 0.6.0

### LINKED ISSUE #14: Depend on upstream crates
Right now, several of the crates are being pulled from GitHub or my filesystem directly. We'll want to wait until local changes have been merged upstream.

### PR DESCRIPTION
**Pull request by mgattozzi**
@crawford I've pushed the release and I'm putting in a PR here to update it for you as well! Thanks for the changes upstream. They're really neat. Feel free to ping me or send in PRs as you need more features. :D

Closes #14

### CODE REVIEW

**Comment by crawford** [comment]
@mgattozzi Thanks for the pull request. The tailor validation is failing both rules (the commit message needs a body and the title needs to have a scope) but it's failing to post the failure because it's more than 140 characters (https://github.com/coreos/tailor/issues/25).

Using a commit message like the following should work:

```
cargo: update github-rs to 0.6.0

github-rs now has all of the necessary changes upstream.
```

**Comment by mgattozzi** [comment]
@crawford reworded the PR should be good to go!

**Comment by crawford** [comment]
@mgattozzi perfect. I'll let the CI finish up and then merge this. Thanks again for all of your help!

**Comment by mgattozzi** [comment]
@crawford thanks for adding things. I haven't really had time to improve the library as much as I'd like so it's real helpful to have others add some great features and implement more endpoints.

**Pull request merged**
